<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MoravianStar_Demo.Maintenance.WebAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MoravianStar.WebAPI" Version="1.52.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoravianStar-Demo.Maintenance.Core\MoravianStar-Demo.Maintenance.Core.csproj" />
    <ProjectReference Include="..\MoravianStar-Demo.Maintenance.Services\MoravianStar-Demo.Maintenance.Services.csproj" />
  </ItemGroup>

</Project>
