<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MoravianStar_Demo.Mobile.WebAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DataAnnotatedModelValidations" Version="5.2.0" />
    <PackageReference Include="ElmahCore" Version="2.1.2" />
    <PackageReference Include="ElmahCore.Sql" Version="2.1.2" />
    <PackageReference Include="GraphQL.Server.Ui.Voyager" Version="8.0.3" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.9.14" />
    <PackageReference Include="MoravianStar.WebAPI" Version="1.24.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoravianStar-Demo.Mobile.Services\MoravianStar-Demo.Mobile.Services.csproj" />
  </ItemGroup>

</Project>
