// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoravianStar_Demo.Persistence.DbContexts;
using NetTopologySuite.Geometries;

#nullable disable

namespace DataLayer.Persistence.Migrations.DataLayer_System
{
    [DbContext(typeof(DataLayer_SystemContext))]
    [Migration("20220114132818_4")]
    partial class _4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CS_AS")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ClientEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientEntityId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("MainAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainAddressId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Point>("CurrentLocation")
                        .HasColumnType("geography");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ClientVehicle");
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.AddressEntity", b =>
                {
                    b.HasOne("DataLayer.Common.Core.Entities.Test.ClientEntity", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ClientEntityId");
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.ClientEntity", b =>
                {
                    b.HasOne("DataLayer.Common.Core.Entities.Test.AddressEntity", "MainAddress")
                        .WithMany()
                        .HasForeignKey("MainAddressId");

                    b.Navigation("MainAddress");
                });

            modelBuilder.Entity("ClientVehicle", b =>
                {
                    b.HasOne("DataLayer.Common.Core.Entities.Test.VehicleEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Common.Core.Entities.Test.ClientEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DataLayer.Common.Core.Entities.Test.ClientEntity", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
