<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>MoravianStar_Demo.Web.Core</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MoravianStar" Version="1.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoravianStar-Demo.Common.Core\MoravianStar-Demo.Common.Core.csproj" />
  </ItemGroup>

</Project>
